name: Serverless CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          cd serverless-platform
          pip install fastapi pymongo uvicorn python-dotenv

      - name: Check Docker is installed and running
        run: |
          docker --version
          docker ps -a || echo "Docker not running"

      - name: Check MongoDB connectivity
        run: |
          sudo apt-get install -y mongodb-clients
          mongosh --host localhost --eval "db.stats()"

      - name: Run FastAPI app (dummy test)
        run: |
          cd serverless-platform
          echo "FastAPI app or tests would run here"
