name: Serverless CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd serverless-platform
          pip install fastapi pymongo uvicorn python-dotenv

      - name: Run test script or server
        run: |
          cd serverless-platform
          # Replace with actual test or uvicorn run command
          echo "Tests or app launch would go here"
